---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    environment: dev
    app.kubernetes.io/name: cloudnotes
    app.kubernetes.io/part-of: cloudnotes
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    environment: staging
    app.kubernetes.io/name: cloudnotes
    app.kubernetes.io/part-of: cloudnotes
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    environment: prod
    app.kubernetes.io/name: cloudnotes
    app.kubernetes.io/part-of: cloudnotes
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: cloudnotes
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/part-of: cloudnotes