{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "auth-service.fullname" . }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "auth-service.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      path: /metrics
      scheme: http
      tlsConfig:
        insecureSkipVerify: false
{{- end }}