---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-service
  namespace: monitoring
  labels:
    team: cloudnotes
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: auth-service
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
  namespaceSelector:
    matchNames:
      - dev
      - staging
      - prod
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: note-service
  namespace: monitoring
  labels:
    team: cloudnotes
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: note-service
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
  namespaceSelector:
    matchNames:
      - dev
      - staging
      - prod
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-service
  namespace: monitoring
  labels:
    team: cloudnotes
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: user-service
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
  namespaceSelector:
    matchNames:
      - dev
      - staging
      - prod
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: analytics-service
  namespace: monitoring
  labels:
    team: cloudnotes
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: analytics-service
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
  namespaceSelector:
    matchNames:
      - dev
      - staging
      - prod
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx
  namespace: monitoring
  labels:
    team: cloudnotes
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: controller
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
  namespaceSelector:
    matchNames:
      - ingress-nginx